#!/usr/bin/env python3

import re
import sys

#Playback 108 [85%] [-14.25dB] [on]

lastLine = None
for line in sys.stdin:
    lastLine = line

_,_,_,vol,_,state = list(filter(lambda s: s != '', re.split(r'\[|\]|\s+', lastLine)))

if state == "off":
    print("MUTE")
else:
    print(vol)


